name: Deploy Master

on:
  push:
    branches:
      - master

jobs:
  curl-call:
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          curl -f --location --request POST https://training.app.appsmith.com/api/v1/git/deploy/app/660e6adc90079c0d26bcd9bb?branchName=master --header 'Authorization: Bearer ${{ secrets.APIKEY }}'
